// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivcyvveidbfuiccsycml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2Y3l2dmVpZGJmdWljY3N5Y21sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTQ3NzEsImV4cCI6MjA1OTE3MDc3MX0.axD3uqt2D48cMP7-eoCJQK-88uflR3mp3OBLUl3hs2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);